# Generated by Django 5.1.8 on 2026-03-12 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EHR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('consultation_type', models.CharField(choices=[('presencial', 'Presencial'), ('telemedicina', 'Telemedicina')], max_length=20)),
                ('transcription', models.TextField()),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EHR',
                'verbose_name_plural': 'EHRs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_identifier', models.CharField(choices=[('soap_note', 'SOAP Note'), ('prescription', 'Prescription'), ('referral', 'Referral')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ehr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ehr.ehr')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
